name: build

on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.13.6
          run_install: |
            - recursive: false

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint
