name: build

on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: 22.x

      - uses: pnpm/action-setup@v5
        with:
          version: 10.32.1
          run_install: |
            - recursive: false

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint
